Test2/Test2/Test2/Controllers/ChoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Test2.Models;

namespace Test2.Controllers
{
    public class ChoicesController : Controller
    {
        private T1808M_NguyenTruongGiangEntities db = new T1808M_NguyenTruongGiangEntities();

        // GET: Choices
        public ActionResult Index()
        {
            var choices = db.Choices.Include(c => c.QUESTION);
            return View(choices.ToList());
        }

        // GET: Choices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Choice choice = db.Choices.Find(id);
            if (choice == null)
            {
                return HttpNotFound();
            }
            return View(choice);
        }

        // GET: Choices/Create
        public ActionResult Create()
        {
            ViewBag.QUESTION_ID = new SelectList(db.QUESTIONs, "QUESTION_ID", "QUESTION_TEXT");
            return View();
        }

        // POST: Choices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ChoiceID,ChoiceText,isAnswer,isSelected,QUESTION_ID")] Choice choice)
        {
            if (ModelState.IsValid)
            {
                db.Choices.Add(choice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.QUESTION_ID = new SelectList(db.QUESTIONs, "QUESTION_ID", "QUESTION_TEXT", choice.QUESTION_ID);
            return View(choice);
        }

        // GET: Choices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Choice choice = db.Choices.Find(id);
            if (choice == null)
            {
                return HttpNotFound();
            }
            ViewBag.QUESTION_ID = new SelectList(db.QUESTIONs, "QUESTION_ID", "QUESTION_TEXT", choice.QUESTION_ID);
            return View(choice);
        }

        // POST: Choices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ChoiceID,ChoiceText,isAnswer,isSelected,QUESTION_ID")] Choice choice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(choice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.QUESTION_ID = new SelectList(db.QUESTIONs, "QUESTION_ID", "QUESTION_TEXT", choice.QUESTION_ID);
            return View(choice);
        }

        // GET: Choices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Choice choice = db.Choices.Find(id);
            if (choice == null)
            {
                return HttpNotFound();
            }
            return View(choice);
        }

        // POST: Choices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Choice choice = db.Choices.Find(id);
            db.Choices.Remove(choice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Test2/Test2/Test2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Test2/Test2/Test2/Controllers/QuizzController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test2.Models;
using Test2.viewModels;

namespace Test2.Controllers
{
    public class QuizzController : Controller
    {
        public T1808M_NguyenTruongGiangEntities dbContext = new T1808M_NguyenTruongGiangEntities();

        // GET: Quizz
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetUser(UserVM user)
        {
            UserVM userConnected = dbContext.CANDIDATEs.Where(u => u.USERNAME == user.Username && u.PASS == user.Pass)
                                         .Select(u => new UserVM
                                         {
                                             UserID = u.CANDIDATE_ID,
                                             Username = u.USERNAME,
                                             Pass = u.PASS,

                                         }).FirstOrDefault();

            UserVM wrongPass = dbContext.CANDIDATEs.Where(u => u.USERNAME == user.Username && u.PASS != user.Pass)
                                         .Select(u => new UserVM
                                         {
                                             UserID = u.CANDIDATE_ID,
                                             Username = u.USERNAME,
                                             Pass = u.PASS,

                                         }).FirstOrDefault();

            if (userConnected != null)
            {
                Session["UserConnected"] = userConnected;
                return RedirectToAction("SelectQuizz");
            }
            else
            {
                ViewBag.Msg = "Error : User is not found !!";
                if (wrongPass != null) { ViewBag.Msg = "Wrong Password"; }
                return View();
            }
        }

        [HttpGet]
        public ActionResult SelectQuizz()
        {
            QuizVM quiz = new viewModels.QuizVM();
            quiz.ListOfQuizz = dbContext.EXAM_SUBJECT.Select(q => new SelectListItem
            {
                Text = q.NAME,
                Value = q.SUBJECT_ID.ToString()

            }).ToList();

            return View(quiz);
        }

        [HttpPost]
        public ActionResult SelectQuizz(QuizVM quiz)
        {
            QuizVM quizSelected = dbContext.EXAM_SUBJECT.Where(q => q.SUBJECT_ID == quiz.QuizID).Select(q => new QuizVM
            {
                QuizID = q.SUBJECT_ID,
                QuizName = q.NAME,

            }).FirstOrDefault();

            if (quizSelected != null)
            {
                Session["SelectedQuiz"] = quizSelected;

                return RedirectToAction("QuizTest");
            }

            return View();
        }

        [HttpGet]
        public ActionResult QuizTest()
        {
            QuizVM quizSelected = Session["SelectedQuiz"] as QuizVM;
            IQueryable<QuestionVM> questions = null;

            if (quizSelected != null)
            {
                questions = dbContext.QUESTIONs.Where(q => q.SUBJECT_ID == quizSelected.QuizID)
                   .Select(q => new QuestionVM
                   {
                       QuestionID = q.QUESTION_ID,
                       QuestionText = q.QUESTION_TEXT,
                       Choices = q.Choices.Select(c => new ChoiceVM
                       {
                           ChoiceID = c.ChoiceID,
                           ChoiceText = c.ChoiceText
                       }).ToList()

                   }).AsQueryable();


            }
            return View(questions);
        }

        [HttpPost]
        public ActionResult QuizTest(List<QuizAnswersVM> resultQuiz)
        {
            List<QuizAnswersVM> finalResultQuiz = new List<viewModels.QuizAnswersVM>();

            foreach (QuizAnswersVM answser in resultQuiz)
            {
                QuizAnswersVM result = dbContext.Answers.Where(a => a.QUESTION_ID == answser.QuestionID).Select(a => new QuizAnswersVM
                {
                    QuestionID = a.QUESTION_ID.Value,
                    AnswerQ = a.AnswerText,
                    isCorrect = (answser.AnswerQ.ToLower().Equals(a.AnswerText.ToLower()))

                }).FirstOrDefault();

                finalResultQuiz.Add(result);
            }

            return Json(new { result = finalResultQuiz }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GradePoint(UserVM userVM)
        {
            CANDIDATE userConnected = (from user in dbContext.CANDIDATEs where user.CANDIDATE_ID == userVM.UserID select user).Single();
            userConnected.PHONE = userVM.Score;
            dbContext.Entry(userConnected).State = EntityState.Modified;
            dbContext.SaveChanges();

            return Json(new { success = true, message = "MonkaS" }, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("GetUser"); 
        }
    }
}

Test2/Test2/Test2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<<div class="row">
    <div class="col-md-4">
        <h2>Information Question </h2>
        <p>

        </p>
        <p><a> @Html.ActionLink("Question", "Index", "QUESTIONs") Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Choose Choice</h2>
        <p></p>
        <p><a @Html.ActionLink("Choice", "Index", "Choices")>Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>About Answer</h2>
        <p></p>
        <p><a @Html.ActionLink("Answer", "Index", "ANSWERs")>Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Information Candidate
        </h2>
        <p><a @Html.ActionLink("Candidate","Index","CANDIDATEs")>Learn more &raquo;</a></p>
    </div>
</div>

Test2/Test2/Test2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<div class="row">
    <div class="col-md-4">
        <h2>You can Register for Exam </h2>
        <p>

        </p>
        <p><a> @Html.ActionLink("Register", "Create", "CANDIDATEs") Learn more &raquo;</a></p>
    </div>
</div>
<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Test2/Test2/Test2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1></h1>
    <p class="lead">The Webster organisation is the leading organization in the world of Oil-Gas Company.  They have various branches throughout the world.  It has various bonds with different multi-national company. The company wants an application to be build for the jobseeker where the entire candidate as per to the criteria will appear for the online test and based on the result of this the candidate will go for further rounds.  .</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>General Knowledge </h2>
        <p>
           
        </p>
        <p><a> @Html.ActionLink("Start Exam","GetUser","Quizz") Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Mathematics</h2>
        <p></p>
        <p><a @Html.ActionLink("Start Exam","GetUser","Quizz")>Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Computer Technology</h2>
        <p></p>
        <p><a @Html.ActionLink("Start Exam","GetUser","Quizz")>Learn more &raquo;</a></p>
    </div>
</div>